import { solution7_1, solution7_2 } from './solutions/7';
import { solution1_1, solution1_2 } from './solutions/1';
import { solution2_1, solution2_2 } from './solutions/2';
import { solution3_1, solution3_2 } from './solutions/3';
import { solution4_1, solution4_2 } from './solutions/4';
import { solution5_1, solution5_2 } from './solutions/5';
import { solution6_1, solution6_2 } from './solutions/6';
import { solution8_1, solution8_2 } from './solutions/8';
import { solution9_1, solution9_2 } from './solutions/9';
import { solution10_1, solution10_2 } from './solutions/10';
import { solution11_1, solution11_2 } from './solutions/11';

(async () => {
  // console.log('solution1_1: ', await solution1_1());
  // console.log('solution1_2: ', await solution1_2());
  // console.log('solution2_1: ', await solution2_1());
  // console.log('solution2_2: ', await solution2_2());
  // console.log('solution3_1: ', await solution3_1());
  // console.log('solution3_2: ', await solution3_2());
  // console.log('solution4_1: ', await solution4_1());
  // console.log('solution4_2: ', await solution4_2());
  // console.log('solution5_1: ', await solution5_1());
  // console.log('solution5_2: ', await solution5_2());
  // console.log('solution6_1: ', await solution6_1());
  // console.log('solution6_2: ', await solution6_2());
  // console.log('solution7_1: ', await solution7_1());
  // console.log('solution7_2: ', await solution7_2());
  // console.log('solution8_1: ', await solution8_1());
  // console.log('solution8_2: ', await solution8_2());
  // console.log('solution9_1: ', await solution9_1());
  // console.log('solution9_2: ', await solution9_2());
  // console.log('solution10_1: ', await solution10_1());
  // console.log('solution10_2: ', await solution10_2());
  // console.log('solution11_1: ', await solution11_1());
  console.log('solution11_2: ', await solution11_2());
})();
